### ISSUE TITLE
Export fails with "AttributeError: 'NoneType' object has no attribute 'inputs" in Blender 2.8

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot-blender-exporter#190]
**OS:**
Manjaro Linux 18.0.3

**Godot version:**
`master` / 8b231b96

**Blender version:**
Blender : 2.8 beta / 84820e
Exporter : `blender2.8` / 22d2f396

**Issue description:**
After I update the exporter from a14b44d to 22d2f396, I'm no longer able to export my model as it fails with the following message:

```
[INFO]: Exporting Blender Object: Head
Traceback (most recent call last):
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/__init__.py", line 205, in execute
    return export_godot.save(self, context, **keywords)
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/export_godot.py", line 292, in save
    exp.export()
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/export_godot.py", line 249, in export
    self.export_scene()
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/export_godot.py", line 205, in export_scene
    self.export_object(obj, root_gd_node)
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/export_godot.py", line 153, in export_object
    self.export_object(child, exported_node)
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/export_godot.py", line 125, in export_object
    parent_gd_node)
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/converters/mesh.py", line 45, in export_mesh_node
    mesh_id = mesh_exporter.export_mesh(escn_file, export_settings)
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/converters/mesh.py", line 165, in export_mesh
    export_settings,
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/converters/mesh.py", line 218, in make_arrays
    mesh
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/converters/mesh.py", line 369, in generate_surfaces
    mat
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/converters/material/material.py", line 53, in export_material
    escn_file, export_settings, material
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/converters/material/material.py", line 79, in generate_material_resource
    escn_file, export_settings, material, mat
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/converters/material/script_shader/node_tree.py", line 322, in export_script_shader
    surface_output_socket = mtl_output_node.inputs['Surface']
AttributeError: 'NoneType' object has no attribute 'inputs
```

**Comment by Jason0214** [comment]
should be fixed by #190

**Comment by mysticfall** [comment]
That was fast :) Thanks!
